#!/usr/bin/env python3
"""Write simulation/iq_results.ods (LibreOffice) from the iq_*.json files.
Sign: positive = delivered by the source. Charges net of baseline, fC; peaks uA; quiescent A."""
import os,sys
import pandas as pd
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
import analyze_iq as A
SIM=A.SIM
def pk(r,s,e):
    v=A.IP(r,s,e); return None if v is None else v[0]
def rows_for(tb,mode):
    out=[]
    for r in A.load(tb,mode):
        d={}
        if mode=='pvt': d.update({'corner':r['corner'],'T_C':r['T'],'VDDL_V':r['vddl'],'VDDH_V':r['vddh']})
        if mode=='tr': d['TR_s']=r['tr']
        for s,n in (('h','VDDH'),('l','VDDL'),('i','in')):
            for st in ('lo','hi'): d[f'Iq_{n}_in{st}_A']=A.IQ(r,s,st)
        for s,n in (('h','VDDH'),('l','VDDL'),('i','in')):
            for e,en in (('r','rise'),('f','fall')): d[f'Q_{n}_{en}_fC']=A.Q(r,s,e)
        for s,n in (('h','VDDH'),('l','VDDL'),('i','in')):
            for e,en in (('r','rise'),('f','fall')): d[f'Ipk_{n}_{en}_uA']=pk(r,s,e)
        out.append(d)
    return pd.DataFrame(out)
notes=pd.DataFrame({'Notes':[
 'Level shifters ls_up_1v2_3v3 and ls_dn_3v3_1v2, IHP SG13CMOS5L, ngspice + PSP103, pre-layout, no parasitics.',
 'Sign: positive current/charge = delivered BY the source. Charge net of pre-edge baseline current, window = edge start .. 10 ns after the input is done.',
 'Rise/fall refer to the INPUT edge. CL = 20 fF unless stated; TR sweep at tt, 27 C, VDDL 1.2 V, VDDH 3.3 V.',
 'PVT sheets: 5 MOS corners x -40/27/125 C x (VDDL,VDDH) = (1.08,3.6), (1.2,3.3), (1.32,3.0); TR = 100 ps.',
 'Quiescent values at pA/fA level are model-limited (checked against simulator gmin 1e-12/1e-15/1e-18: no change).',
 'ls_dn has no VDDH: VDDH columns are empty for it.',
 'Point VDDL=1.08 V, sf, -40 C of ls_up has delays of 6-9 ns: edge of the working range.',
 'Source: scripts/run_iq.py, scripts/analyze_iq.py, simulation/iq_*.json; generated by scripts/gen_ods.py.']})
out=os.path.join(SIM,'iq_results.ods')
with pd.ExcelWriter(out,engine='odf') as w:
    notes.to_excel(w,sheet_name='Notes',index=False)
    for tb in ('tb_ls_up','tb_ls_dn'):
        n=tb[3:]
        for mode,name in (('tr','TR'),('pvt','PVT'),('cload','CL')):
            df=rows_for(tb,mode)
            if mode=='cload':
                df.insert(0,'CL_F',[r['cload'] for r in A.load(tb,mode)])
            df.dropna(axis=1,how='all').to_excel(w,sheet_name=f'{n}_{name}',index=False)
print('wrote',out)
